version: "3"

services:
  bitrix-notification-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Personal
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13.10
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
