//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarNotificationBot.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarNotificationBot.Domain.Resources.Resources.SharedResource", typeof(Resources_SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar was deleted.
        /// </summary>
        internal static string CalendarDeleted_Message {
            get {
                return ResourceManager.GetString("CalendarDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar link.
        /// </summary>
        internal static string CalendarLink_Message {
            get {
                return ResourceManager.GetString("CalendarLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar was not deleted &apos;cause calendar or user was not found.
        /// </summary>
        internal static string CalendarNotDeleted_Message {
            get {
                return ResourceManager.GetString("CalendarNotDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Calendar was not found*.
        /// </summary>
        internal static string CalendarNotFound_Message {
            get {
                return ResourceManager.GetString("CalendarNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar was updated.
        /// </summary>
        internal static string CalendarUpdated_Message {
            get {
                return ResourceManager.GetString("CalendarUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Timezone.
        /// </summary>
        internal static string ChangeTimezone_Menu {
            get {
                return ResourceManager.GetString("ChangeTimezone_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action:.
        /// </summary>
        internal static string ChooseAction_Menu {
            get {
                return ResourceManager.GetString("ChooseAction_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share telegram account data.
        /// </summary>
        internal static string ContactData_Menu {
            get {
                return ResourceManager.GetString("ContactData_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update contact data.
        /// </summary>
        internal static string DataNotUpdated_Message {
            get {
                return ResourceManager.GetString("DataNotUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact data updated.
        /// </summary>
        internal static string DataUpdated_Message {
            get {
                return ResourceManager.GetString("DataUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete calendar.
        /// </summary>
        internal static string DeleteCalendar_Menu {
            get {
                return ResourceManager.GetString("DeleteCalendar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View profile.
        /// </summary>
        internal static string Information_Menu {
            get {
                return ResourceManager.GetString("Information_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calendar link is in an incorrect format. You need to send only a link to a file with the .ICS extension..
        /// </summary>
        internal static string MalformedLink_Message {
            get {
                return ResourceManager.GetString("MalformedLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bot is designed to notify users about upcoming events in the provided calendar.
        ///The calendar is supplied via a link to an .ICS file, which can be obtained from Bitrix24 or other platforms..
        /// </summary>
        internal static string Registration_Message {
            get {
                return ResourceManager.GetString("Registration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share telegram account data for registration.
        /// </summary>
        internal static string ShareContactData_Message {
            get {
                return ResourceManager.GetString("ShareContactData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone was changed to &apos;{0}&apos;.
        /// </summary>
        internal static string TimezoneChanged_Message {
            get {
                return ResourceManager.GetString("TimezoneChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update calendar.
        /// </summary>
        internal static string UpdateCalendar_Menu {
            get {
                return ResourceManager.GetString("UpdateCalendar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide the calendar link:
        ///            
        ///            In Bitrix24, navigate to: Profile &gt; Calendar &gt; Calendars.
        ///            Click the three dots next to the desired calendar and select Export (iCal).
        ///            Copy the generated link..
        /// </summary>
        internal static string UpdateCalendar_Message {
            get {
                return ResourceManager.GetString("UpdateCalendar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update contact data.
        /// </summary>
        internal static string UpdateContactData_Menu {
            get {
                return ResourceManager.GetString("UpdateContactData_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update contact data with telegram profile.
        /// </summary>
        internal static string UpdateContactDataFromAccount_Menu {
            get {
                return ResourceManager.GetString("UpdateContactDataFromAccount_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set your time zone:
        ///Enter your time zone in the format GMT\\-\\+0.
        ///For example: GMT\\-0, GMT\\+3..
        /// </summary>
        internal static string UpdateTimezone_Message {
            get {
                return ResourceManager.GetString("UpdateTimezone_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Username*\: {0}
        ///*Name*\: {1} {2}
        ///*User id*\: {3}
        ///*Chat Id*\: {4}
        ///{5}.
        /// </summary>
        internal static string UserInfo_Message {
            get {
                return ResourceManager.GetString("UserInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound_Message {
            get {
                return ResourceManager.GetString("UserNotFound_Message", resourceCulture);
            }
        }
    }
}
