//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarNotificationBot.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_SharedResource_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SharedResource_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalendarNotificationBot.Domain.Resources.Resources.SharedResource.ru-RU", typeof(Resources_SharedResource_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календарь удалён.
        /// </summary>
        internal static string CalendarDeleted_Message {
            get {
                return ResourceManager.GetString("CalendarDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на календарь.
        /// </summary>
        internal static string CalendarLink_Message {
            get {
                return ResourceManager.GetString("CalendarLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календарь не был удалён так как пользователь или календарь не найден.
        /// </summary>
        internal static string CalendarNotDeleted_Message {
            get {
                return ResourceManager.GetString("CalendarNotDeleted_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Календарь отсутствует*.
        /// </summary>
        internal static string CalendarNotFound_Message {
            get {
                return ResourceManager.GetString("CalendarNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календарь обновлён.
        /// </summary>
        internal static string CalendarUpdated_Message {
            get {
                return ResourceManager.GetString("CalendarUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить часовой пояс.
        /// </summary>
        internal static string ChangeTimezone_Menu {
            get {
                return ResourceManager.GetString("ChangeTimezone_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие:.
        /// </summary>
        internal static string ChooseAction_Menu {
            get {
                return ResourceManager.GetString("ChooseAction_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться контактными данные телеграм.
        /// </summary>
        internal static string ContactData_Menu {
            get {
                return ResourceManager.GetString("ContactData_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные не обновлены.
        /// </summary>
        internal static string DataNotUpdated_Message {
            get {
                return ResourceManager.GetString("DataNotUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные обновлены успешно.
        /// </summary>
        internal static string DataUpdated_Message {
            get {
                return ResourceManager.GetString("DataUpdated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить календарь.
        /// </summary>
        internal static string DeleteCalendar_Menu {
            get {
                return ResourceManager.GetString("DeleteCalendar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string Information_Menu {
            get {
                return ResourceManager.GetString("Information_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на календарь в неправильном формате.
        ///            Необходимо отправить только ссылку на скачивание файла с расширением .ICS.
        /// </summary>
        internal static string MalformedLink_Message {
            get {
                return ResourceManager.GetString("MalformedLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный бот предназначен для нотификации пользователей о предстоящих событиях в предоставленном календаре.
        ///Календарь предоставляется ссылкой на .ICS файл, который можно найти как в битриксе так и на других платформах..
        /// </summary>
        internal static string Registration_Message {
            get {
                return ResourceManager.GetString("Registration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте контактные данные в бота для регистрации.
        /// </summary>
        internal static string ShareContactData_Message {
            get {
                return ResourceManager.GetString("ShareContactData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для пользователя установлена таймзона &apos;{0}&apos;.
        /// </summary>
        internal static string TimezoneChanged_Message {
            get {
                return ResourceManager.GetString("TimezoneChanged_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить календарь.
        /// </summary>
        internal static string UpdateCalendar_Menu {
            get {
                return ResourceManager.GetString("UpdateCalendar_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставьте ссылку на календарь.
        ///Для экспорта календаря в битрексе необходимо пройти по следующему пути: Профиль -&gt; Календарь -&gt; Календари -&gt; Три точки напротив нужного календаря -&gt; Экспорт iCal -&gt; Копировать ссылку.
        /// </summary>
        internal static string UpdateCalendar_Message {
            get {
                return ResourceManager.GetString("UpdateCalendar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить контактные данные.
        /// </summary>
        internal static string UpdateContactData_Menu {
            get {
                return ResourceManager.GetString("UpdateContactData_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить контактные данные через контакты.
        /// </summary>
        internal static string UpdateContactDataFromAccount_Menu {
            get {
                return ResourceManager.GetString("UpdateContactDataFromAccount_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваш часовой пояс в формате *GMT\\-\\+0*\\.
        ///Например *GMT\\-0*, *GMT\\+3*\\..
        /// </summary>
        internal static string UpdateTimezone_Message {
            get {
                return ResourceManager.GetString("UpdateTimezone_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Тэг пользователя*\: {0}
        ///*Имя*\: {1} {2}
        ///*Id пользователя*\: {3}
        ///*Id чата*\: {4}
        ///{5}.
        /// </summary>
        internal static string UserInfo_Message {
            get {
                return ResourceManager.GetString("UserInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string UserNotFound_Message {
            get {
                return ResourceManager.GetString("UserNotFound_Message", resourceCulture);
            }
        }
    }
}
